### ISSUE TITLE
local option uses /local which isn't mapped in docker

### ISSUE THREAD

**Issue by kylerw** [andrey-git/home-assistant-customizer#1]
Error loading state-card-custom-ui from /local/custom_ui/state-card-state-card-custom-ui.html

my config is in: /config so the files should be in /config/www/custom_ui

**Comment by andrey-git** [comment]
`/local/custom_ui/` is not the filesystem path, it is the the url.

However it says "state-card-state-card-custom-ui.html" so this probably doesn't come from customizer but from an old (maybe cached) version of HA frontend looking at a new config (saying `custom_ui_state_card: state-card-custom-ui`)

Try to clear cache or force refresh (Ctrl+Shift+R / Ctrl+F5)

**Comment by andrey-git** [comment]
@kylerw did force-refreshing help?

**Comment by kylerw** [comment]
I was able to fix it. The refresh seemed to do the trick but oddly, not the first time. So I'm not sure what the issue was exactly. But, its now resolved. Thanks for the quick feedback.
