### ISSUE TITLE
Editing icon

### ISSUE THREAD

**Issue by cogneato** [andrey-git/home-assistant-customizer#2]
When editing an icon and saving, the page refreshes to show "mdi:mdi:icon-name" which implies that mdi isn't needed and is being duplicated. If the extra mdi is removed, the edit will not be saved properly.

**Comment by gohassgo** [comment]
The icon field has "mdi:" fixed, implying that you only need to enter an icon name. Doing so only add the icon name to /config/customize.yaml, like:
  icon: lightbulb
The icon of course does not appear. Entering "mdi:[icon_name]" in the field works and the icon is shown. This results in mdi:mdi:icon appearing in the customizer field, but enters correctly in customize.yaml.
  icon: mdi:lightbulb

**Comment by andrey-git** [comment]
This was fixed by https://github.com/home-assistant/home-assistant-polymer/pull/423

**Comment by cogneato** [comment]
Just saw the .53.1 fix and previous reports of the same issue. Hassio user here and a little behind, sorry.
